#!/usr/bin/env bash
set -euo pipefail

: "${LORE_DIR:?LORE_DIR is not set}"

die() {
    [ $# -eq 0 ] || echo fatal: "$@" >&2
    exit 1
}

lgit() {
    env GIT_AUTHOR_DATE='@0 +0000' \
        GIT_COMMITTER_DATE='@0 +0000' \
        GIT_AUTHOR_NAME='Lore' \
        GIT_COMMITTER_NAME='Lore' \
        GIT_AUTHOR_EMAIL='lore@example.com' \
        GIT_COMMITTER_EMAIL='lore@example.com' \
        git --git-dir="$LORE_DIR" "$@"
}

cmd_init() {
    if [[ -e "$LORE_DIR" ]]; then
        printf 'lore: %s already exists\n' "$LORE_DIR" >&2
        exit 1
    fi
    mkdir -p "$LORE_DIR"
    lgit init --bare --quiet
}

# $1: blob name
hf_blob() {
    [ -n "$1" ] || return 1;
    printf '100644 blob %s\t%s\n' $(lgit hash-object -w --stdin) "$1"
}

cmd_init_trace() {
    printf 'LOREv1' | hf_blob _LORETRACE | lgit mktree
}

# add-key <key> <trace>
cmd_add_key() {
    local key="$1"
    local tob="$2"

    # FIXME: check here if tob is corrupted (i.e. multiple same key occur)
    local kob=$(lgit ls-tree "$tob" | awk -v k="$key" '$4 == k { print $3 }')

    if [ -n "$kob" ]; then
        die $key already exists on trace $tob
    else
        # The current structure is inefficient because a garbage tree
        # accumulates during the creation process. There is a need to
        # migrate to commands like index-key.
        {
            lgit ls-tree $tob
            hf_blob "$key"
        } | lgit mktree
    fi
}

# chain-trace [-p <chain>] <trace>
cmd_chain_trace() {
    local parent=
    local trace=

    if [[ $# -eq 1 ]]; then
        trace="$1"
    elif [[ $# -eq 3 && "$1" == "-p" ]]; then
        parent="-p $2"
        trace="$3"
    else
        die "Usage: chain-trace [-p <chain>] <trace>"
    fi

    lgit commit-tree $parent $trace </dev/null
}

main() {
    [[ $# -lt 1 ]] && { echo "usage: lore-cas <cmd> [args]" >&2; exit 1; }
    local cmd="$1"; shift
    local fn="cmd_${cmd//-/_}"
    if declare -F "$fn" > /dev/null; then
        "$fn" "$@"
    else
        printf 'lore-cas: unknown command %q\n' "$cmd" >&2
        exit 1
    fi
}
main "$@"
