#!/usr/bin/env bash
source lib.bash

usage() {
    cat <<EOF
usage: ${NAME} [--no-auth] [--no-stream] [-p <chain-ish>] [-e ENDPOINT] [-m MODEL]
  -e, --endpoint     API endpoint (default \$PLM_ENDPOINT)
  -m, --model        Model name   (default \$PLM_MODEL)
  -p, --parent       Parent chain-ish to chain on (default HEAD)
  -t, --tag          Update-ref <ref> with chain pointing by HEAD before ask
  -n, --new          Start new converastion
  -r, --resend       Do not accept input
      --no-stream    Disable streaming (PLM_USE_STREAM=false)
      --no-auth      Do not require API key (PLM_API_KEY_REQUIRED=0)
  -h, --help         Show this help
EOF
}

main() {
    local parent=HEAD parent_arg= resend= ref=

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help)        usage; exit 0 ;;
            -e|--endpoint)    export PLM_ENDPOINT="${2:?$1 requires arg}"; shift 2 ;;
            -m|--model)       export PLM_MODEL="${2:?$1 requires arg}"; shift 2 ;;
            -p|--parent)      parent="${2:?$1 requires arg}"; shift 2 ;;
            -t|--tag)         ref="${2:?$1 requires arg}"; shift 2 ;;
            -n|--new)         parent=; shift ;;
            -r|--resend)      resend=1; shift ;;
            --no-stream)      export PLM_USE_STREAM='false'; shift ;;
            --no-auth)        export PLM_API_KEY_REQUIRED=0; shift ;;
            -*|*)             echo "unknown arg: $1" >&2; usage; exit 1 ;;
        esac
    done

    [[ -n $resend && -z $parent ]] && die "--new --resend doesn't make sense"

    [[ -n $ref ]] && sib update-ref -m 'ask: add tag by -t' \
                         "$ref" "$(sib rev-parse HEAD)"

    # TODO: dedup refs/conv/scratch with sib init
    [[ -z $parent ]] && sib symbolic-ref -m 'ask: start new conversation' \
                            HEAD refs/conv/scratch

    # --new sets parent= to make chain-trace-json create a new root
    # chain. If no arguments are passed to rev-parse, nothing is
    # printed. Therefore, $parent become empty here as well.
    parent="$(sib rev-parse $parent 2>/dev/null || true)"

    # rev-parse prints empty means there is no ref pointed to by
    # $parent. In this case, start a new chain and update HEAD.
    parent_arg="${parent:+-p $parent}"

    {
        if [[ -z $resend ]]; then
            [[ -t 0 ]] && echo '(stdin, Ctrl+D to send)' >&2

            plm-wrap -f text -t plm | sib chain-trace-json $parent_arg
        elif [[ -n $parent ]]; then
            echo $parent
        fi
    } | xargs -r sib update-ref -m 'ask: chain user turn' HEAD

    sib rev-jsonl HEAD \
        | plm-wrap -f plm -t request \
        | plm-send \
        | plm-wrap -f response -t plm -r assistant \
        | sib chain-trace-json -p HEAD \
        | xargs sib update-ref -m 'ask: chain agent turn' HEAD
}

# Human-readable message will be streamed to fd 3 by plm-send. Bind
# fd 3 to this script's stdout so users can pipe the message.
main "$@" 3>&1
