#!/usr/bin/env bash
. lib.bash

usage() {
    cat <<EOF
usage: ${NAME} [-s <refname>] [-h] <chain-ish>
       ${NAME} [-s <refname>] [-f] <ref>

Move HEAD to <chain-ish>. By default, HEAD is detached at the resolved
chain
  -s  save HEAD to <refname> before switch
  -f  HEAD follows <ref> after switch
  -h  print this help
EOF
}

symbolic= refname=
while getopts hfs: o; do
    case $o in
        h) usage; exit 0 ;;
        f) symbolic=true ;;
        s) refname="$OPTARG" ;;
        *) usage; exit 1 ;;
    esac
done
shift $((OPTIND - 1))

[[ $# -eq 1 ]] || { usage >&2; exit 1; }
chain="$1"

[[ -n $refname ]] && sib save "$refname"

is_ref() {
    sib show-ref "$1" >/dev/null 2>&1
}

if [[ -n $symbolic ]]; then
    is_ref "$chain" || die "-f set but $chain is not ref"
    sib symbolic-ref -m "switch to symbolic $chain" HEAD "$chain"
else
    res=$(sib rev-parse "$chain" 2>/dev/null) || die "$chain is invalid"
    sib update-ref -m "switch to $chain" --no-deref HEAD $res
fi
