#!/usr/bin/env bash
source lib.bash

usage() {
    cat <<EOF
usage: ${NAME} [-k <KEY>] [-n <LINES>] [<chain-ish>]
  -n LINES    Truncate content to LINES
  -k KEY      Only show KEY's value on chain
  -h, --help  Show this help
EOF
}

n_lines= key=
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help) usage; exit 0 ;;
        -n)        n_lines="${2:?$1 requires arg}"; shift 2 ;;
        -k)        key="${2:?$1 requires arg}"; shift 2 ;;
        -*)        echo "unknown arg: $1" >&2; usage; exit 1 ;;
        *)         break ;;
    esac
done

render() {
    cat | sed 's/^/    /' && true;
}

truncate_content() {
    [[ -n $n_lines ]] && head -n "$n_lines" || cat
}

target=${1:-HEAD}
chain=$(sib rev-parse $target)

if [[ ! -z $key ]]; then
    sib ls-trace $chain \
        | awk -v k=$key '$1 == k { print $2 }' \
        | xargs sib git cat-file blob
    exit 0
fi

# Normal output
echo "chain $chain"

CONTENT=content

# Traverse all key except $CONTENT
sib ls-trace $chain | awk -v k="$CONTENT" '$1 != k { print }' \
    | while IFS=$' ' read -r key value; do

    # Capitalize first letter
    key=$(printf '%s' "${key^}:")
    value=$(sib git cat-file blob $value)
    echo "$key $value"
done

printf '\n'
sib ls-trace $chain | awk -v k="$CONTENT" '$1 == k { print $2 }' \
    | xargs sib git cat-file blob \
    | truncate_content | render
printf '\n'
